version: '3'

services:
  db:
    image: postgres:11-alpine
    container_name: task_manager_postgres
    user: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: task_manager_db

    ports:
      - "5432:5432"

volumes:
  postgres-data:
    driver: local